name : a test workflow

on : 
    push: 
        branches:["main"]

jobs: 
    testing-testing:
          runs-on : ubuntu-latest
          steps:
          #1. steps under the job follows
              - name: welcome people
                run: echo "welcome to class"

                #step 2.
                - name: tell people goodbye
                  run: echo "Goodbye class"

